### ISSUE TITLE
Update to MPSS 3.1.1

### ISSUE THREAD

**Issue by nanoant** [xdsopl/mpss-modules#1]
Any chance to have it updated to MPSS 3.1.1, or post some instructions how to make it in par with latest release.

Best regards, and thank you for your effort,
Adam

**Comment by xdsopl** [comment]
Thanks for the info of a newer version .. didn't have much time for playing with mic lately :(

Please checkout "devel" branch, test and tell me how good it works, so i can merge it to "master" branch.

Ahmet

**Comment by xdsopl** [comment]
Iv'e just updated the host system to mpss 3.1.1 and Linux-3.12.3.
Did some testing and everything looks good so far.
Merged the update from "devel" to "master".

Ahmet
