### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by sambo57u** [xdsopl/mpss-modules#4]
Hi,  I am using the daemon with mpss-3.2.1 and with kernel 3.13.10 (using the new metadata file). I presume no other changes are needed so perhaps one can make a new repelase for 3.2.1.
Next I would like to go to 3.14.x (I am on Fedora 20 using mpss-3.2.1). The module compiled ok. Will you be testing/porting to 3.14.x?
Sait Umar
PS: Your name is Turkish. I am Turkish as well.

**Comment by xdsopl** [comment]
Really didn't have the opportunity to test the 3.2.1 release, so thanks for testing.
Did the mpss-modules-3.2.1 release for Linux-3.13 just now.
On Linux-3.14 im seeing some sysfs->kernfs changes.
I'm on a run, so i will come back to you with a proper patch for Linux-3.14 later.
Ahmet

**Comment by sambo57u** [comment]
I just tested 3.14.1 on Fedora 20 and the module loaded and I could log in.
It seems
like it is working but it would be good to check.

On a related topic, my mpssd daemon was taking 100% of cpu all the time
(working fine
otherwise). I had sent some debug outputs to the xeon phi forum and this
morning I got
the attached patch that completely fixed the problem.

Sait

On Wed, Apr 23, 2014 at 9:24 AM, Ahmet Inan notifications@github.comwrote:

> Really didn't have the opportunity to test the 3.2.1 release, so thanks
> for testing.
> Did the mpss-modules-3.2.1 release for Linux-3.13 just now.
> On Linux-3.14 im seeing some sysfs->kernfs changes.
> I'm on a run, so i will come back to you with a proper patch for
> Linux-3.14 later.
> Ahmet
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xdsopl/mpss-modules/issues/4#issuecomment-41166767
> .

## 

_Prof. Dr. Sait Umar_
_Vanderbilt University_
_Dept. of Physics & Astronomy_
_Box 1807, Station B_
_Nashville, TN 37235_
_Tel : +1-615-322-2459_
http://compsci.cas.vanderbilt.edu/~umar/resume.pdf

**Comment by xdsopl** [comment]
Please Checkout the "devel" Branch.
It has an trivial fix for Linux-3.14, equivalent to the one made in the in-tree mic module.
If it works well, i would like to hear from you again so i can release it.
Thanks for the hint with the fixed mpssd problem, that patch can be found here:
https://software.intel.com/en-us/forums/topic/509387#comment-1786852
Ahmet

**Comment by sambo57u** [comment]
I built the devel branch and running on 3.14.1 fine (it was running before
that small
change as well).

Yes, the blog where that patch is actually mine!
Thanks
Sait

On Thu, Apr 24, 2014 at 3:32 AM, Ahmet Inan notifications@github.comwrote:

> Please Checkout the "devel" Branch.
> It has an trivial fix for Linux-3.14, equivalent to the one made in the
> in-tree mic module.
> If it works well, i would like to hear from you again so i can release it.
> Thanks for the hint with the fixed mpssd problem, that patch can be found
> here:
> https://software.intel.com/en-us/forums/topic/509387#comment-1786852
> Ahmet
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/xdsopl/mpss-modules/issues/4#issuecomment-41255799
> .

## 

_Prof. Dr. Sait Umar_
_Vanderbilt University_
_Dept. of Physics & Astronomy_
_Box 1807, Station B_
_Nashville, TN 37235_
_Tel : +1-615-322-2459_
http://compsci.cas.vanderbilt.edu/~umar/resume.pdf

**Comment by xdsopl** [comment]
Thanks for testing.
Updated Release mpss-3.2.1 to Linux-3.14.
Ahmet
