### ISSUE TITLE
suppoort for kernels 4.xx

### ISSUE THREAD

**Issue by sl1pkn07** [xdsopl/mpss-modules#8]
Hi

any plans to support kernels >4.x?

i want to build the mpss module for my archlinux, bug get this fail when build with kernel 4.0.7

http://sl1pkn07.wtf/paste/view/dd237964

and with all branch for you repo (devel-3.4, vanilla, etc). no success

greetings

**Comment by xdsopl** [comment]
Hi Gustavo,
unfortunately I don't have access to a Xeon Phi System anymore so I wont be doing much maintenance on this port in the future.
But lucky for you, devel-3.4 compiles just fine on vanilla linux-4.0 and linux-4.1.
I just cherry-picked all the needed changes from devel-3.4 on top of devel-3.3, if that was the version you needed.
Please try again and report back.
Greetings,
Ahmet

**Comment by sl1pkn07** [comment]
oh, yes, you are right, the devel-3.4 build ok with my kernel (i clone the repo, but i forget change the branch XD)

ok then.

one little question, is hard to implement to new MPSS 3.5.1?

greetings

**Comment by xdsopl** [comment]
Update to mpss-3.5.1 was trivial. Please check it out and report back, so I can make a release.
Ahmet

**Comment by msteggink** [comment]
Hi, I just built the modules from development (devel-3.5) on a clean CentOS 6.6 installation with kernel (kernel-ml-4.1.3-1.el6.elrepo.x86_64.rpm). make && make install works out of the box.

modinfo mic

filename:       /lib/modules/4.1.3-1.el6.elrepo.x86_64/extra/mic.ko
license:        GPL
build_scmver:   5c2298f5c59a5aaa74df6d07f860b983cd11e45d
build_ondate:   2015-08-02 19:51:36 +0200
srcversion:     B73911AFC8E1A3F3AAF83EB

Created Sun Aug  2 20:08:36 2015

```
    System Info
            HOST OS                 : Linux
            OS Version              : 4.1.3-1.el6.elrepo.x86_64
            Driver Version          : 3.5.1-1
            MPSS Version            : 3.5.1
            Host Physical Memory    : 23599 MB
```

**Comment by xdsopl** [comment]
Thank you for testing.
Just made a release.

Ahmet

**Comment by sl1pkn07** [comment]
fail build win kernel 4.2.x

http://sl1pkn07.wtf/paste/view/6d5dc853

greetings
